name: zinngle_app4
description: A Flutter application for connecting creators and fans.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  provider: ^6.0.5
  http: ^0.13.5
  supabase_flutter: ^2.10.3
  cached_network_image: ^3.2.3
  smooth_page_indicator: ^1.1.0
  country_code_picker: ^3.0.0
  image_picker: ^1.0.4
  audioplayers: ^5.2.1
  agora_rtc_engine: ^6.2.1
  razorpay_flutter: ^1.3.0
  fl_chart: ^0.66.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  uuid: ^4.2.1
  connectivity_plus: ^6.0.3
  package_info_plus: ^8.0.0
  flutter_dotenv: ^6.0.0
  flutter_form_builder: ^10.0.1
  flutter_rating_bar: ^4.0.1
  permission_handler: ^11.3.1
  flutter_ringtone_player: ^4.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env